name: test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Start Server
        run: docker-compose up -d web
      - name: E2E Testing
        working-directory: __test__
        run: pip3 install -r requirements.txt && python3 test.py
      - name: Archive Screen Shots
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: selenium-failed-screenshots
          path: __test__/screens/**/*.png
          if-no-files-found: ignore
