name: test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Retrieve Python Libraries from Cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Retrieve Docker Image from ~/.cache/pip
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        with:
          key: ${{ runner.os }}-docker-${{ hashFiles('**/dockerfile', '**/docker-compose.yml') }}
          restore-keys: |
            ${{ runner.os }}-docker-
      - name: Start Server
        run: docker-compose up -d web
      - name: E2E Testing
        working-directory: __test__
        run: pip3 install -r requirements.txt && python3 test.py -v
      - name: Archive Screen Shots
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: selenium-failed-screenshots
          path: __test__/screens/**/*.png
          if-no-files-found: ignore
